
# Meta Data for SEO

## Homepage
title = "M3TASERVE"
logo = "/images/m3taserve.svg"
titleSeparator = "-"
titleAddition = "Become a Web3 dev, land your next job!"
description = "M3TASERVE is the Web3 education academy for developers, by developers"

## Open Graph + Twitter Cards
images = ["/images/og-preview-image.png", "/images/header-logo.svg"]
twitterSite = "m3taserve"
twitterCreator = "m3taserve"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "/images/og-preview-image.png"
schemaTwitter = "https://twitter.com/m3taserve"
schemaLinkedIn = "https://www.linkedin.com/"
schemaGitHub = "https://github.com/M3TASERVE"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/M3TASERVE/website"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
